day13/urls.py
# from django.contrib import admin
from django.urls import path
from www.views import acount

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('login/', acount.login, name="login"),
    path('sms/login/', acount.sms_login, name='sms_login'),
    path('sms/send/', acount.send_sms, name='send_sms'),
    path('home/', acount.home, name='home'),

]

www/models.py
from django.db import models


class ActiveBaseModel(models.Model):
    active = models.SmallIntegerField(verbose_name="状态", default=1, choices=((1, "激活"), (0, "删除"),))

    class Meta:
        abstract = True


class Administrator(ActiveBaseModel):
    """ 管理员表 """
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    mobile = models.CharField(verbose_name="手机号", max_length=11, db_index=True)
    create_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True)


class Level(ActiveBaseModel):
    """ 级别表 """
    title = models.CharField(verbose_name="标题", max_length=32)
    percent = models.IntegerField(verbose_name="折扣", help_text="填入0-100整数表示百分比，例如：90，表示90%")

    def __str__(self):
        return self.title


class Customer(ActiveBaseModel):
    """ 客户表 """
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    mobile = models.CharField(verbose_name="手机号", max_length=11, db_index=True)
    # mobile = models.CharField(verbose_name="手机号", max_length=11, db_index=True, validators=[RegexValidator(r'^\d{11}$', '手机号格式错误'), ], )
    balance = models.DecimalField(verbose_name="账户余额", default=0, max_digits=10, decimal_places=2)
    level = models.ForeignKey(verbose_name="级别", to="Level", on_delete=models.CASCADE)
    # level = models.ForeignKey(verbose_name="级别", to="Level", on_delete=models.CASCADE, limit_choices_to={'active': 1})
    create_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True)
    creator = models.ForeignKey(verbose_name="创建者", to="Administrator", on_delete=models.CASCADE)


class PricePolicy(models.Model):
    """ 价格策略（原价，后续可以根据用级别不同做不同折扣）
    1  1000 10
    2  2000 18
    """
    count = models.IntegerField(verbose_name="数量")
    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)


class Order(ActiveBaseModel):
    """ 订单表 """
    status_choices = (
        (1, "待执行"),
        (2, "正在执行"),
        (3, "已完成"),
        (4, "失败"),
        (5, "已撤单"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)

    # 202211022123123123
    oid = models.CharField(verbose_name="订单号", max_length=64, unique=True)
    url = models.URLField(verbose_name="视频地址", db_index=True)
    count = models.IntegerField(verbose_name="数量")

    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)
    real_price = models.DecimalField(verbose_name="实际价格", default=0, max_digits=10, decimal_places=2)

    old_view_count = models.CharField(verbose_name="原播放量", max_length=32, default="0")

    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    customer = models.ForeignKey(verbose_name="客户", to="Customer", on_delete=models.CASCADE)
    memo = models.TextField(verbose_name="备注", null=True, blank=True)


class TransactionRecord(ActiveBaseModel):
    """ 交易记录 """
    charge_type_class_mapping = {
        1: "success",
        2: "danger",
        3: "default",
        4: "info",
        5: "primary",
    }
    charge_type_choices = ((1, "充值"), (2, "扣款"), (3, "创建订单"), (4, "删除订单"), (5, "撤单"),)
    charge_type = models.SmallIntegerField(verbose_name="类型", choices=charge_type_choices)

    customer = models.ForeignKey(verbose_name="客户", to="Customer", on_delete=models.CASCADE)
    amount = models.DecimalField(verbose_name="金额", default=0, max_digits=10, decimal_places=2)

    creator = models.ForeignKey(verbose_name="管理员", to="Administrator", on_delete=models.CASCADE, null=True, blank=True)

    order_oid = models.CharField(verbose_name="订单号", max_length=64, null=True, blank=True, db_index=True)
    create_datetime = models.DateTimeField(verbose_name="交易时间", auto_now_add=True)
    memo = models.TextField(verbose_name="备注", null=True, blank=True)

www/forms/account.py
import random

from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django_redis import get_redis_connection
from www.utils.encrypt import md5_string
from www import models
from www.utils import tencent
from www.utils.bootstrap import BootStrapForm


class LoginForms(BootStrapForm, forms.Form):
    # exclude_field_list = ['role']
    role = forms.ChoiceField(
        label='角色',
        required=True,
        choices=((2, '客户'), (1, '管理员'))
    )

    username = forms.CharField(
        label='用户名',
        required=True,
        widget=forms.TextInput
    )

    password = forms.CharField(
        label='密码',
        required=True,
        widget=forms.PasswordInput(render_value=True)
    )

    def clean_password(self):
        old = self.cleaned_data['password']
        return md5_string(old)


class SmsLoginForms(BootStrapForm, forms.Form):
    role = forms.ChoiceField(
        label='角色',
        required=True,
        choices=((2, '客户'), (1, '管理员'))
    )

    mobile = forms.CharField(
        label='手机号',
        required=True,
    )

    code = forms.CharField(
        label='验证码',
        required=True,
        widget=forms.PasswordInput
    )

    def clean_code(self):
        mobile = self.cleaned_data['mobile']
        code = self.cleaned_data['code']

        if not mobile:
            return code
        conn = get_redis_connection('default')
        cache_code = conn.get(mobile)
        if not cache_code:
            raise ValidationError('未发送或已失效')

        if code != cache_code.decode('utf-8'):
            raise ValidationError('验证码错误！')

        conn.delete(mobile)
        return code


class SendSmsForm(forms.Form):
    role = forms.ChoiceField(
        label='角色',
        required=True,
        choices=((2, '客户'), (1, '管理员'))
    )
    mobile = forms.CharField(
        label='手机号',
        required=True,
        widget=forms.TextInput,
        validators=[RegexValidator(r'^1[3578]\d{9}$', '手机号码格式不正确')]
    )

    def clean_mobile(self):
        role = self.cleaned_data.get('role')
        old = self.cleaned_data['mobile']
        if role == "1":
            exists = models.Administrator.objects.filter(active=1).filter(mobile=old).exists()
        else:
            exists = models.Customer.objects.filter(active=1).filter(mobile=old).exists()

        if not exists:
            raise ValidationError('手机号码不存在！')

        sms_code = random.randint(00000, 99999)
        print('生成的随机码为：', sms_code)
        if_ok = tencent.send_sms(old, sms_code)
        if not if_ok:
            raise ValidationError('短信发送失败！')

        conn = get_redis_connection('default')
        conn.set(old, sms_code, ex=5 * 60)

        return old

www/views/acount.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from www.forms import account
from www import models


def login(request):
    if request.method == "GET":
        form = account.LoginForms()
        return render(request, 'login.html', {'forms': form})

    form = account.LoginForms(data=request.POST)
    if not form.is_valid():
        return render(request, 'login.html', {'forms': form})

    data_dict = form.cleaned_data
    role = data_dict.pop('role')
    if role == "1":
        user_object = models.Administrator.objects.filter(active=1).filter(**data_dict).first()
    else:
        user_object = models.Administrator.objects.filter(active=1).filter(**data_dict).first()

    if not user_object:
        form.add_error({'password': '用户名或密码错误!'})
        return render(request, 'login.html', {'forms': form})

    mapping = {"1": 'ADMIN', '2': 'CUSTOMER'}
    request.session["user_info"] = {
        'role': mapping[role],
        'id': user_object.id,
        "username": user_object.username
    }

    return redirect(settings.HOME_URL)


def sms_login(request):
    if request.method == "GET":
        form = account.SmsLoginForms()
        return render(request, 'sms_login.html', {'forms': form})

    form = account.SmsLoginForms(data=request.POST)
    if not form.is_valid():
        return render(request, 'sms_login.html', {'forms': form})

    # data_dict = form.cleaned_data
    role = form.cleaned_data['role']
    mobile = form.cleaned_data['mobile']
    if role == "1":
        user_object = models.Administrator.objects.filter(mobile=mobile).filter(active=1).first()
    else:
        user_object = models.Administrator.objects.filter(mobile=mobile).filter(active=1).first()

    if not user_object:
        return JsonResponse({"state": False, 'msg': {'mobile': "手机号不能为空"}})

    mapping = {"1": 'ADMIN', '2': 'CUSTOMER'}
    request.session["user_info"] = {
        'role': mapping[role],
        'id': user_object.id,
        "username": user_object.username
    }
    return JsonResponse({'state': True, "msg": 'OK', 'data': settings.HOME_URL})


@csrf_exempt
def send_sms(request):
    form = account.SendSmsForm(data=request.POST)
    if not form.is_valid():
        return JsonResponse({'state': False, "msg": form.errors})

    return JsonResponse({'state': True, "msg": "OK"})

def home(request):
    username = request.nb_name.username

    return render(request,'home.html',{"username":username})

www/templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>{{ username }},欢迎访问NB系统</h2>
</body>
</html>

www/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .box {
            width: 450px;
            border: 1px solid #f0f0f0;
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;

            padding-left: 40px;
            padding-right: 40px;
            padding-bottom: 30px;

            box-shadow: 5px 10px 10px rgb(0 0 0 / 5%);
        }
    </style>
</head>
<body>
<div class="box">
    <h2 style="text-align: center">用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in forms %}
            <div class="form-group" style="position: relative;margin-bottom: 25px;">
                <label>{{ field.label }}</label>
                {{ field }}
                <span style="color:red;position: absolute;">{{ field.errors.0 }}</span>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">登 录</button>
        <a href="{% url 'sms_login' %}" style="float: right">短信登录</a>
    </form>
</div>
</body>
</html>

www/templates/sms_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .box {
            width: 450px;
            border: 1px solid #f0f0f0;
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;

            padding-left: 40px;
            padding-right: 40px;
            padding-bottom: 30px;

            box-shadow: 5px 10px 10px rgb(0 0 0 / 5%);
        }

        .error-message {
            position: absolute;
            color: red;
        }
    </style>
</head>
<body>
<div class="box">
    <h2 style="text-align: center">用户登录</h2>
    <form method="post" novalidate id="smsForm">
        {% csrf_token %}
        {% for field in forms %}
            {% if field.name == 'code' %}
                <div class="form-group" style="position: relative;margin-bottom: 25px">
                    <label>{{ field.label }}</label>
                    <div class="row">
                        <div class="col-xs-7">
                            {{ field }} <span class="error-message">{{ field.errors.0 }}</span>
                        </div>
                        <div class="col-xs-5">
                            <input type="button" value="点击获取验证码" id="btnSendSms" class="btn btn-default">
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="form-group" style="position: relative;margin-bottom: 25px">
                    <label>{{ field.label }}</label>
                    {{ field }}
                    <span class="error-message">{{ field.errors.0 }}</span>
                </div>
            {% endif %}
        {% endfor %}
        <input type="submit" value="提 交" id="btnSubmit" class="btn btn-default"/>
        <a href="{% url 'login' %}" style="float: right;">用户名登录</a>
    </form>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script>
    $(function () {
        bindSendSmsEvent();
        bindSubmitEvent();
    })

    function bindSendSmsEvent() {
        $('#btnSendSms').click(function () {
            $('.error-message').empty();
            $.ajax({
                url: "{% url 'send_sms' %}",
                type: 'POST',
                data: {
                    'mobile': $('#id_mobile').val(),
                    'role': $('#id_role').val()
                },
                dataType: 'JSON',
                success: function (res) {
                    console.log(res)
                    if (res.state) {
                        $('#btnSendSms').prop("disabled", true)
                        var time = 10
                        var remind = setInterval(function () {
                            $('#btnSendSms').val(time + '秒重新发送！')
                            time = time - 1;
                            if (time < 1) {
                                $('#btnSendSms').val('重新发送验证码')
                                clearInterval(remind);
                                $('#btnSendSms').prop("disabled", false);
                            }
                        }, 1000)
                    } else {
                        $.each(res.msg, function (k, v) {
                            console.log(k, v)
                            $('#id_' + k).next().text(v[0]);
                        })
                    }
                }
            })
        })
    }

    function bindSubmitEvent() {
        $('#btnSubmit').click(function () {
            $('.msg-error').empty();
            $.ajax({
                url: "{% url 'sms_login' %}",
                type: "POST",
                data: $('#smsForm').serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.state) {
                        location.href = res.data;
                    } else {
                        $.each(res.msg, function (k, v) {
                            $('#id_' + k).next().text(v[0]);
                        })
                    }


                }

            })
        })
    }
</script>
</body>
</html>